#!/bin/bash

echo "🚀 Personal Calendar Database Setup"
echo "📅 Complete setup for personal calendar functionality"
echo ""
echo "⚠️  IMPORTANT: You need to run this SQL in your Supabase Dashboard > SQL Editor"
echo ""
echo "📋 Copy and paste the following SQL into Supabase SQL Editor:"
echo ""
echo "=================================================="
echo ""
cat create_personal_calendar_tables.sql
echo ""
echo "=================================================="
echo ""
echo "✅ After running the SQL in Supabase, your personal calendar will be ready!"
echo ""
echo "🎯 Features included:"
echo "   • Personal events with recurring support"
echo "   • Task management integrated with calendar"
echo "   • Time blocks for focus time"
echo "   • Timetable meetings integration"
echo "   • 12-hour time format support"
echo "   • Month/Week/Day views"
echo "   • Smooth new event creation"
echo "   • Working hours highlighting"
echo ""
echo "🔗 Access your calendar at: /my-personal"
echo ""
echo "💡 The sidebar already has the 'My Personal' link added!" 