# Generated by Django 5.2.3 on 2025-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_meeting_assignee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="assignee",
        ),
    ]
